"""empty message

Revision ID: 1087fbe8ef22
Revises: bc0f7ab6c794
Create Date: 2021-10-22 10:16:35.996094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1087fbe8ef22'
down_revision = 'bc0f7ab6c794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notebooks_note_id_fkey', 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'note_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('notebooks_note_id_fkey', 'notebooks', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
