"""empty message

Revision ID: 091efd2bb95a
Revises: 
Create Date: 2021-10-27 11:01:06.560028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091efd2bb95a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notebooks', ['title'])
    op.create_foreign_key(None, 'notebooks', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'notes', ['title'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.drop_constraint(None, 'notebooks', type_='unique')
    # ### end Alembic commands ###
